### ISSUE TITLE
First issue when opening the project

### ISSUE THREAD

**Issue by MaherJendoubi** [mdymel/AspNetCoreAngular2#1]
![image](https://cloud.githubusercontent.com/assets/1798510/18620090/06cb3798-7e0c-11e6-8f66-ab3f9b84738c.png)

**Comment by mdymel** [comment]
You need to install dotnet core tools - follow the link 'click here' and install required tools. You can also use this link: https://www.microsoft.com/net/download

**Comment by MaherJendoubi** [comment]
So you are not updated to 1.0.1? I have already installed .NET SDK 1.0.1

**Comment by mdymel** [comment]
Ah! Sorry, I haven't. Just update the tools section in the `project.json` file.
